server:
  port: 8086

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authentication?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: nam30101999
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false
  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            data:
              redis: RedisAutoConfiguration

redis:
  host: 127.0.0.1
  port: 6379
